apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitops-observability-backend-chart.fullname" . }}
  labels:
      {{- include "gitops-observability-backend-chart.labels" . | nindent 4 }}
data: {{- (tpl (.Files.Glob "configuration/*").AsConfig . ) | nindent 2 }}
